# Generated by Claude.
# Common variables for Alexandria infrastructure

variable "region" {
  description = "AWS region"
  type        = string
  default     = "eu-central-1"
}

variable "authentication_domain" {
  description = "Domain for federated authentication"
  type        = string
  default     = "platform-idp-auth.isnan.eu"
}

variable "bedrock_model" {
  description = "Bedrock model ID for card detection"
  type        = string
  default     = "eu.anthropic.claude-sonnet-4-6"
}
